### C: connect函数出现EINTR时的正确处理方法

#### 1.connect的EINTR处理方法是一个例外

UNP 5.9最后一段中论述了socket网络编程中常见的低速系统调用被信号中断后的EINTR错误的一般处理方法——重启，但是其中特别指出了一个例外：即`connect`函数遇到EINTR错误时不能重启。

![](/assets/c045_01.PNG)

其中他特别指出了，重启因为EINTR返回的`connect`函数会立即返回一个错误，但是会返回何种错误、为什么会立即返回错误这里都没有指明。

#### 2.connect出现EINTR不能重启的原因

国外网站的一个很详细的解释：[http://www.madore.org/~david/computers/connect-intr.html](http://www.madore.org/~david/computers/connect-intr.html)

其中核心内容摘录如下：

```
The reference for connect() (hereafter, “the Spec”) is part of the Open Group's Single Unix Specification, version 3 (note: you may need to register to read this; see also here). Here is the relevant part of it:

If the initiating socket is connection-mode, then connect() shall attempt to establish a connection to the address specified by the address argument. If the connection cannot be established immediately and O_NONBLOCK is not set for the file descriptor for the socket, connect() shall block for up to an unspecified timeout interval until the connection is established. If the timeout interval expires before the connection is established, connect() shall fail and the connection attempt shall be aborted. If connect() is interrupted by a signal that is caught while blocked waiting to establish a connection, connect() shall fail and set connect() to [EINTR], but the connection request shall not be aborted, and the connection shall be established asynchronously.

If the connection cannot be established immediately and O_NONBLOCK is set for the file descriptor for the socket, connect() shall fail and set errno to [EINPROGRESS], but the connection request shall not be aborted, and the connection shall be established asynchronously. Subsequent calls to connect() for the same socket, before the connection is established, shall fail and set errno to [EALREADY].

When the connection has been established asynchronously, select() and poll() shall indicate that the file descriptor for the socket is ready for writing.

Later on, when listing possible error codes for connect(), the Spec mentions:

The connect() function shall fail if:

[…]
[EALREADY]
A connection request is already in progress for the specified socket.
```